version: '3.6'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - HOSTNAME=http://localhost:8080
      - REDIRECT_URI=http://localhost:8080
      - CLIENT_ID=CLIENT_ID
      - CLIENT_SECRET=CLIENT_SECRET
    volumes:
      - ./app/:/app
    ports:
      - 8000:80
